{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "vsan-observability.namespace" . }}
  labels:
    {{- include "vsan-observability.labels" . | nindent 4 }}
{{- end }}
