apiVersion: v1
kind: Secret
metadata:
  name: vsan-influx
  namespace: {{ include "vsan-observability.namespace" . }}
  labels:
    {{- include "vsan-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
type: Opaque
stringData:
  admin-user: {{ .Values.influxdb.credentials.adminUser | quote }}
  admin-password: {{ .Values.influxdb.credentials.adminPassword | quote }}
  admin-token: {{ .Values.influxdb.credentials.adminToken | quote }}
  org: {{ .Values.influxdb.credentials.org | quote }}
  bucket: {{ .Values.influxdb.credentials.bucket | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vsan-grafana
  namespace: {{ include "vsan-observability.namespace" . }}
  labels:
    {{- include "vsan-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.credentials.adminUser | quote }}
  admin-password: {{ .Values.grafana.credentials.adminPassword | quote }}
